services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./prisma:/app/prisma
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_postgres_crud
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
